name: CI


on: [push, workflow_dispatch]


jobs:

  build:


    runs-on: windows-latest


    steps:

    - name: Download

      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract

      run: Expand-Archive ngrok.zip

    - name: Auth

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS

      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Create Tunnel

      run: .\ngrok\ngrok.exe tcp 3389

Public Last updated: 2023-08-17 11:52:06 AM

Comments
Rebin  •  3 months 1 day ago Reply
Good bro
Milton  •  2 months 29 days ago Reply
Not Workes
EHTASHAM  •  2 months 27 days ago Reply
working smooth. thnx
not work  •  2 months 21 days ago Reply
not work received error
ci  •  2 months 15 days ago Reply
ci
Auth error  •  2 months 12 days ago Reply
Recived Auth error : 
Error: Process completed with exit code 1.

AAA  •  19 days ago Reply
It works thx
github  •  14 days ago Reply
we will ban who use this
GitHub  •  13 days ago Reply
Your data will be hacked
AAA  •  12 days ago Reply
@GitHub  don care still don care
Githubbelike  •  11 days ago Reply
@AAA I will Buy U😂😂😎 
Your Name
Comment

Download on the Apple Store   Get it on Google Play

© 2009-2023 aNotepad.com

About | Privacy | Features | Resume Builder | Free Fax | Report Abuse

aNotepad.com is your everyday online notepad. You can take notes and share notes online without having to login.
You can use a rich text editor and download your note as PDF or Word document.
Best of all - aNotepad is a fast, clean, and easy-to-use notepad online.


